Blog date appearance
openwebdocs/owd-website pull request #35
Opened 2022-09-12 19:30 UTC by estelle

Make the dates italic and offset the color a bit.

2022-09-13 07:32 UTC, Elchi3 reviewed
This doesn't match the `.byline ` style on the posts itself. Should it?

2022-09-14 06:12 UTC, estelle commented
the color (opacity) does. The byline, however, is not italic.

2022-09-14 07:23 UTC, Elchi3 commented
I'd say let's make both italic or neither of them.

2022-09-20 18:49 UTC, Elchi3 requested changes

2022-09-20 18:49 UTC, Elchi3 commented on assets/css/general.css
> +}
```suggestion
h2 + small {
  opacity: 50%;
}
```

2022-09-29 02:53 UTC, merged